version: '3.3'

services:
  django:
    build: ./
    command: "gunicorn tdregionsnab.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app/api
      - static_volume:/static
      - media_volume:/media
    env_file:
      - '.env'
    expose:
      - 8000

volumes:
  static_volume:
  media_volume: