# Generated by Django 4.1.3 on 2022-11-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': 'Картинка к слайдеру новости', 'verbose_name_plural': 'Картинки к слайдеру новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='prev_image',
            field=models.ImageField(default=0, upload_to=None, verbose_name='Картинка к карточке'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='slider_image', verbose_name='Картинка'),
        ),
    ]
