# Generated by Django 4.1.3 on 2022-11-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_news_options_alter_newsimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='partnerShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField()),
                ('first_name', models.TextField()),
                ('patronymic', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
            ],
            options={
                'verbose_name': 'Заявка на сотрудничество',
                'verbose_name_plural': 'Заявки на сотрудничество',
            },
        ),
    ]
