# Generated by Django 4.1.3 on 2022-11-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_partnership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_desc',
            field=models.CharField(max_length=254, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='first_name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='patronymic',
            field=models.TextField(verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='phone',
            field=models.TextField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='surname',
            field=models.TextField(verbose_name='Фамилия'),
        ),
    ]
