# Generated by Django 4.1.3 on 2022-11-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_news_short_desc_alter_partnership_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_desc',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
    ]
